[project]
name = "800-pharmacy-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "numpy",
    "streamlit",
    "openpyxl",
    "python-dotenv",
]

[tool.setuptools.packages.find]
where = ["src"]